site_name: Koila
theme:
  name: material
  font:
    text: Open Sans
    code: Fira Code
  icon:
    repo: material/github
edit_uri: README.md
repo_name: rentruewang/koila
repo_url: https://github.com/rentruewang/koila
plugins:
  - git-revision-date:
      enabled_if_env: CI
  - git-revision-date-localized:
      type: date
