[tool.poetry]
name = "koila"
version = "0.1.1"
description = "Prevent PyTorch's `CUDA error out of memory` in a few lines of code."
authors = ["rentruewang <patrick1031wang@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22.0"
torch = "^1.10.1"
rich = "^10.16.1"
pynvml = "^11.4.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.12b0"
mkdocs = "^1.2.3"
mkdocs-material = "^8.1.3"
autoflake = "^1.4"
isort = "^5.10.1"
coverage = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
include = ["koila"]
exclude = [
    "**/node_modules",
    "**/__pycache__",
    "src/experimental",
    "src/typestubs",
]

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.8"
pythonPlatform = "Linux"
