name: Unit Testing
on: [push]
jobs:
  unit-test-py38:
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v2

      - name: 🏗️ python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: ⬇️ Library Dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: requirements/prod.txt
          update-pip: true
          update-setuptools: true
          update-wheel: true
      - name: ⬇️ Development Dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: requirements/dev.txt
          update-pip: true
          update-setuptools: true
          update-wheel: true
      - name: 🏃 pytest
        run: pytest -v

  unit-test-py39:
    runs-on: ubuntu-latest
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v2

      - name: 🏗️ python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: ⬇️ Python Dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: requirements.txt
          update-pip: true
          update-setuptools: true
          update-wheel: true
      - name: ⬇️ pytest coverage
        run: pip install pytest coverage
      - name: 🏃 pytest
        run: coverage run -m pytest -v
      - name: 📊 coverage
        run: coverage report -m
